### ISSUE TITLE
WDS

### ISSUE THREAD

**Issue by resistdesign** [d6u/webpack-loader#2]
You may want to do this for WDS: https://github.com/webpack/webpack-dev-middleware/blob/master/middleware.js#L34

**Comment by resistdesign** [comment]
Or probably set it to the current instance from the parent compiler.

I'm still not sure that will get you complete compatibility with WDS and hot loading.

**Comment by resistdesign** [comment]
And I'm not sure it'll work with https://github.com/gaearon/react-hot-loader

**Comment by resistdesign** [comment]
I'll be trying things and I'll let you know what happens either way.

**Comment by d6u** [comment]
Hi, @resistdesign, thanks for checking out. Not sure I understand what you are trying to accomplish. Could explain you goal so I will see if I can help?

**Comment by resistdesign** [comment]
Ok, so I got this to work perfectly with a modified version of your loader (https://github.com/resistdesign/rdx/blob/master/src/CustomLoaders/HTMLAsset.js) however, WDS uses `memory-fs` which I think you know based on your unused variable. I was trying to make this compatible with WDS. But it does not seem possible given that you can **not** access the object instance where `memory-fs` stores the data for WDS because of some somewhat irresponsible handling of the `outputFileSystem` on behalf of `webpack-dev-middleware` (https://github.com/webpack/webpack-dev-middleware/blob/master/middleware.js#L34).

@d6u Does that make sense?

**Comment by d6u** [comment]
You are trying to develop a server that bundles webpack-dev-middelware and some other plugins, right? 

I created this repo wanting to confirm the requirements within https://github.com/webpack/webpack/issues/536#issuecomment-171868874 (I'm sure you already read it). But got no real feedback. If you have a better idea on how to carry this package forward, we can figure a way to transfer https://www.npmjs.com/package/webpack-loader to you. Let me know what I can help.

**Comment by resistdesign** [comment]
Yes, I did read the comment and that's how I found this. I think it's a brilliant idea and for pure compilation it work amazingly. But what I was telling you is that it will never work with WDS for a number of reasons.
